//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LogicAnalyzer.rc
//
#define ID_TIMER_GUI_UPDATE             101
#define IDD_LOGICANALYZER_DIALOG        102
#define ID_TIMER_CAPTURE_FINISHED       103
#define ID_TIMER_ANALYZE_FINISHED       104
#define IDR_PORTTALK                    120
#define IDR_WINRING_32                  121
#define IDR_WINRING_64                  122
#define IDR_HTML_TEMPLATE               123
#define IDR_HELP                        124
#define IDR_MAINFRAME                   128
#define IDI_ICON_LED_RED                129
#define IDI_ICON_LED_GREEN              130
#define IDI_ICON_LED_GREY               131
#define IDI_ICON_EGGTIMER               134
#define IDI_ICON_PARALLELPORT           135
#define IDC_EDIT_PORT                   1002
#define IDC_BTN_SPEED                   1003
#define IDC_STATIC_SPEED                1004
#define IDC_BTN_HELP                    1004
#define IDC_STATIC_DRIVER               1005
#define IDC_ICON_LINE_0                 1006
#define IDC_LED_DATA_0                  1006
#define IDC_ICON_LINE_1                 1007
#define IDC_LED_DATA_1                  1007
#define IDC_ICON_LINE_2                 1008
#define IDC_LED_DATA_2                  1008
#define IDC_ICON_LINE_3                 1009
#define IDC_LED_DATA_3                  1009
#define IDC_ICON_LINE_4                 1010
#define IDC_LED_DATA_4                  1010
#define IDC_ICON_LINE_5                 1011
#define IDC_LED_DATA_5                  1011
#define IDC_ICON_LINE_6                 1012
#define IDC_LED_DATA_6                  1012
#define IDC_ICON_LINE_7                 1013
#define IDC_LED_DATA_7                  1013
#define IDC_ICON_LINE_8                 1014
#define IDC_LED_STATUS_0                1014
#define IDC_RADIO_CAP_MEM               1015
#define IDC_RADIO_CAP_DISK              1016
#define IDC_LED_STATUS_1                1016
#define IDC_EDIT_MEMSIZE                1017
#define IDC_BTN_CAPTURE                 1018
#define IDC_EDIT_HTML_HEADING           1019
#define IDC_BTN_ANALYZE                 1020
#define IDC_EDIT_OUTFILE                1021
#define IDC_EDIT_START_TIME             1021
#define IDC_CHECK_BIT0                  1022
#define IDC_LED_STATUS_2                1022
#define IDC_CHECK_BIT1                  1023
#define IDC_LED_STATUS_3                1023
#define IDC_CHECK_BIT2                  1024
#define IDC_LED_STATUS_4                1024
#define IDC_CHECK_BIT3                  1025
#define IDC_LED_CTRL_0                  1025
#define IDC_CHECK_BIT4                  1026
#define IDC_LED_CTRL_1                  1026
#define IDC_CHECK_BIT5                  1027
#define IDC_LED_CTRL_2                  1027
#define IDC_CHECK_BIT6                  1028
#define IDC_LED_CTRL_3                  1028
#define IDC_CHECK_BIT7                  1029
#define IDC_EDIT_END_TIME               1029
#define IDC_CHECK_BIT8                  1030
#define IDC_BTN_BROWSE                  1031
#define IDC_RADIO_AUTO_SAMPL            1032
#define IDC_RADIO_FIX_SAMPL             1033
#define IDC_EDIT_SAMPLE_FREQU           1034
#define IDC_STATIC_CAPTURED             1035
#define IDC_STATIC_STATUS_0             1037
#define IDC_STATIC_DATA_7               1038
#define IDC_STATIC_DATA_6               1039
#define IDC_STATIC_DATA_5               1040
#define IDC_STATIC_CTRL_1               1041
#define IDC_CHECK_USE_DATA              1042
#define IDC_CHECK_USE_STATUS            1043
#define IDC_CHECK_USE_CONTROL           1044
#define IDC_STATIC_CTRL_2               1045
#define IDC_STATIC_CTRL_3               1046
#define IDC_STATIC_DATA_0               1047
#define IDC_STATIC_DATA_1               1048
#define IDC_STATIC_DATA_2               1049
#define IDC_STATIC_DATA_3               1050
#define IDC_STATIC_DATA_4               1051
#define IDC_STATIC_STATUS_1             1052
#define IDC_STATIC_STATUS_2             1053
#define IDC_STATIC_STATUS_3             1054
#define IDC_STATIC_STATUS_4             1055
#define IDC_STATIC_CTRL_0               1056
#define IDC_STATIC_EGGTIMER             1057
#define IDC_STATIC_EGGTIMER2            1058
#define IDC_CHECK_AUTO_UNITS            1060
#define IDC_EDIT_RASTER_UNIT            1061
#define IDC_EDIT_IDLE_TIME              1062
#define IDC_CHECK_DEL_OLD_FILES         1063
#define IDC_COMBO_PORT                  1064
#define IDC_COMBO_PROTOCOL              1065
#define IDC_COMBO_BAUDRATE              1066
#define IDC_COMBO_PARITY                1067
#define IDC_COMBO_STOPBITS              1068
#define IDC_EDIT_SPEED                  1069
#define IDC_COMBO_DATABITS              1069
#define IDC_COMBO_DRAWMODE              1070
#define IDC_STATIC_STATUSBAR            1071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
